### Task 0: Logging Setup
Configure application-level logging with the following requirements:

*   Log the start and completion of the overall pipeline.
*   Log the start and end of each task.
*   Capture warnings, errors, and exceptional conditions.
*   Logs must be written to both console and a file.

In [177]:
import logging
import pandas as pd
import numpy as np

logger = logging.getLogger('my_logger')
logger.setLevel(logging.DEBUG)

if logger.hasHandlers():
    logger.handlers.clear()

filehandler = logging.FileHandler('my_logger.log')
filehandler.setLevel(logging.DEBUG)

consolehandler = logging.StreamHandler()
consolehandler.setLevel(logging.DEBUG)

formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

filehandler.setFormatter(formatter)
consolehandler.setFormatter(formatter)

logger.addHandler(filehandler)
logger.addHandler(consolehandler)

logger.info('Started the numpy assignment')

2026-03-11 08:54:14,058 - my_logger - INFO - Started the numpy assignment
INFO:my_logger:Started the numpy assignment

### Task 1: Data Loading
*   Load the `employees.csv` dataset into a suitable in-memory structure.
*   Ensure date fields are parsed correctly.
*   Display a sample of the dataset for verification.
*   Log the total number of records and detected schema.

In [178]:
df = pd.read_csv('/content/employees.csv', parse_dates=['Joining_Date'],dayfirst=True)
logger.info('imported the csv into dataframe')

2026-03-11 08:54:14,076 - my_logger - INFO - imported the csv into dataframe
INFO:my_logger:imported the csv into dataframe

In [179]:
print(df)

    Employee_ID               Name   Age Department   Salary Joining_Date  \
0          1001        Steven Dunn  30.0         IT  46846.0   2024-06-09
1          1002    Jennifer Romero  54.0         IT  43585.0   2018-02-07
2          1003         Dana Haney  59.0    Finance      NaN   2019-01-11
3          1004       Louis Powers  60.0    Finance  58094.0   2019-09-26
4          1005   Jennifer Gilmore  54.0  Marketing  80848.0   2020-02-09
..          ...                ...   ...        ...      ...          ...
95         1096        John Walton  28.0         IT  52401.0   2017-08-13
96         1097  Matthew Alexander  25.0         IT  61221.0   2018-11-18
97         1098         Kelly Cole  25.0         HR  69045.0   2018-07-14
98         1099     Melissa Harper  52.0         IT  61606.0   2022-10-20
99         1100      Paul Price MD   NaN  Marketing  42862.0   2017-12-27

    Resigned
0      False
1      False
2      False
3      False
4      False
..       ...
95      True
96     False
97     False
98      True
99     False

[100 rows x 7 columns]

In [180]:
df.shape
logger.info('shape of the dataframe' + str(df.shape))

2026-03-11 08:54:14,100 - my_logger - INFO - shape of the dataframe(100, 7)
INFO:my_logger:shape of the dataframe(100, 7)

In [181]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Department', 'Salary', 'Joining_Date',
       'Resigned'],
      dtype='object')

In [182]:
logger.info( 'columns of the dataframe' + str(df.columns))

2026-03-11 08:54:14,114 - my_logger - INFO - columns of the dataframeIndex(['Employee_ID', 'Name', 'Age', 'Department', 'Salary', 'Joining_Date',
       'Resigned'],
      dtype='object')
INFO:my_logger:columns of the dataframeIndex(['Employee_ID', 'Name', 'Age', 'Department', 'Salary', 'Joining_Date',
       'Resigned'],
      dtype='object')

In [183]:
df.isna().sum()
logger.info('number of null values in each column' + str(df.isna().sum()))

2026-03-11 08:54:14,127 - my_logger - INFO - number of null values in each columnEmployee_ID      0
Name             0
Age             16
Department       0
Salary           8
Joining_Date     0
Resigned         0
dtype: int64
INFO:my_logger:number of null values in each columnEmployee_ID      0
Name             0
Age             16
Department       0
Salary           8
Joining_Date     0
Resigned         0
dtype: int64

In [184]:
df['Age'] = df['Age'].fillna(df['Age'].median())
logger.info('filled the null values in age column with median')
df

2026-03-11 08:54:14,138 - my_logger - INFO - filled the null values in age column with median
INFO:my_logger:filled the null values in age column with median

,Employee_ID,Name,Age,Department,Salary,Joining_Date,Resigned
0,1001,Steven Dunn,30.0,IT,46846.0,2024-06-09,False
1,1002,Jennifer Romero,54.0,IT,43585.0,2018-02-07,False
2,1003,Dana Haney,59.0,Finance,NaN,2019-01-11,False
3,1004,Louis Powers,60.0,Finance,58094.0,2019-09-26,False
4,1005,Jennifer Gilmore,54.0,Marketing,80848.0,2020-02-09,False
...,...,...,...,...,...,...,...
95,1096,John Walton,28.0,IT,52401.0,2017-08-13,True
96,1097,Matthew Alexander,25.0,IT,61221.0,2018-11-18,False
97,1098,Kelly Cole,25.0,HR,69045.0,2018-07-14,False
98,1099,Melissa Harper,52.0,IT,61606.0,2022-10-20,True
99,1100,Paul Price MD,45.5,Marketing,42862.0,2017-12-27,False

### Task 2: Data Cleaning
*   Identify missing values across all columns.
*   Replace missing `Age` values using the median of the available data.
*   Replace missing `Salary` values using the mean of the available data.
*   Detect and remove duplicate employee records based on `Employee_ID`.
*   Standardize column naming for consistency.
*   Ensure all columns are stored using appropriate data types.
*   Log all cleaning actions performed.

In [185]:
df.isna().sum()

Employee_ID     0
Name            0
Age             0
Department      0
Salary          8
Joining_Date    0
Resigned        0
dtype: int64

In [186]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
logger.info('filled the null values in salary column with mean')
df

2026-03-11 08:54:14,186 - my_logger - INFO - filled the null values in salary column with mean
INFO:my_logger:filled the null values in salary column with mean

,Employee_ID,Name,Age,Department,Salary,Joining_Date,Resigned
0,1001,Steven Dunn,30.0,IT,46846.000000,2024-06-09,False
1,1002,Jennifer Romero,54.0,IT,43585.000000,2018-02-07,False
2,1003,Dana Haney,59.0,Finance,59643.923913,2019-01-11,False
3,1004,Louis Powers,60.0,Finance,58094.000000,2019-09-26,False
4,1005,Jennifer Gilmore,54.0,Marketing,80848.000000,2020-02-09,False
...,...,...,...,...,...,...,...
95,1096,John Walton,28.0,IT,52401.000000,2017-08-13,True
96,1097,Matthew Alexander,25.0,IT,61221.000000,2018-11-18,False
97,1098,Kelly Cole,25.0,HR,69045.000000,2018-07-14,False
98,1099,Melissa Harper,52.0,IT,61606.000000,2022-10-20,True
99,1100,Paul Price MD,45.5,Marketing,42862.000000,2017-12-27,False

In [187]:
df.isna().sum()

Employee_ID     0
Name            0
Age             0
Department      0
Salary          0
Joining_Date    0
Resigned        0
dtype: int64

In [188]:
df.drop_duplicates(subset='Employee_ID')

,Employee_ID,Name,Age,Department,Salary,Joining_Date,Resigned
0,1001,Steven Dunn,30.0,IT,46846.000000,2024-06-09,False
1,1002,Jennifer Romero,54.0,IT,43585.000000,2018-02-07,False
2,1003,Dana Haney,59.0,Finance,59643.923913,2019-01-11,False
3,1004,Louis Powers,60.0,Finance,58094.000000,2019-09-26,False
4,1005,Jennifer Gilmore,54.0,Marketing,80848.000000,2020-02-09,False
...,...,...,...,...,...,...,...
95,1096,John Walton,28.0,IT,52401.000000,2017-08-13,True
96,1097,Matthew Alexander,25.0,IT,61221.000000,2018-11-18,False
97,1098,Kelly Cole,25.0,HR,69045.000000,2018-07-14,False
98,1099,Melissa Harper,52.0,IT,61606.000000,2022-10-20,True
99,1100,Paul Price MD,45.5,Marketing,42862.000000,2017-12-27,False

In [189]:
logger.info('dropped the duplicate values')

2026-03-11 08:54:14,251 - my_logger - INFO - dropped the duplicate values
INFO:my_logger:dropped the duplicate values

In [190]:
df.rename(columns={
    'Employee_ID': 'employee_id',
    'Name': 'name',
    'Salary': 'salary',
    'Age': 'age',
    'Joining_Date': 'joining_date',
    'Resigned': 'resigned',
    'Department': 'department'
}, inplace=True)

In [191]:
logger.info('renamed column into lowercase')

2026-03-11 08:54:14,267 - my_logger - INFO - renamed column into lowercase
INFO:my_logger:renamed column into lowercase

In [192]:
df.dtypes

employee_id              int64
name                    object
age                    float64
department              object
salary                 float64
joining_date    datetime64[ns]
resigned                  bool
dtype: object

In [193]:
df['name']= df['name'].astype('str')
df['department']= df['department'].astype('str')

logger.info('Typecasted the columns datatype')

2026-03-11 08:54:14,293 - my_logger - INFO - Typecasted the columns datatype
INFO:my_logger:Typecasted the columns datatype

In [194]:
df.dtypes

employee_id              int64
name                    object
age                    float64
department              object
salary                 float64
joining_date    datetime64[ns]
resigned                  bool
dtype: object

### Task 3: Data Manipulation
*   Filter out employees who are above the age of 25 or have a salary above 40,000, and are not resigned.
*   Create a new column `YearsInCompany` by calculating the number of years each employee has worked in the company (from `JoiningDate` to today).
*   Record and log the number of records before and after filtering.

In [195]:
fil1 = ((df['age'] > 25) | (df['salary'] > 40000)) & (df['resigned'] == False)
df[fil1]

,employee_id,name,age,department,salary,joining_date,resigned
0,1001,Steven Dunn,30.0,IT,46846.000000,2024-06-09,False
1,1002,Jennifer Romero,54.0,IT,43585.000000,2018-02-07,False
2,1003,Dana Haney,59.0,Finance,59643.923913,2019-01-11,False
3,1004,Louis Powers,60.0,Finance,58094.000000,2019-09-26,False
4,1005,Jennifer Gilmore,54.0,Marketing,80848.000000,2020-02-09,False
6,1007,Thomas Lopez,39.0,HR,66678.000000,2015-05-24,False
10,1011,Steven Macias,59.0,HR,46928.000000,2018-04-02,False
11,1012,Joseph Erickson,45.5,HR,65527.000000,2024-03-03,False
15,1016,Karina Allen,46.0,IT,66746.000000,2019-02-04,False
17,1018,Bryan Golden,30.0,Finance,78126.000000,2015-05-07,False
18,1019,Derrick Cummings,45.5,Marketing,50772.000000,2016-03-14,False
22,1023,Jeffrey Hernandez,43.0,HR,46782.000000,2019-12-09,False
25,1026,Eric Mckinney,48.0,IT,58591.000000,2018-05-08,False
27,1028,Tara Campos,36.0,HR,87226.000000,2022-02-20,False
29,1030,Austin Robinson,45.5,Finance,40249.000000,2021-12-20,False
32,1033,Joshua Meyer,54.0,IT,80900.000000,2017-04-28,False
33,1034,April Yoder,55.0,Finance,53113.000000,2024-07-20,False
36,1037,Jeffery Lawrence,46.0,Finance,48939.000000,2022-12-14,False
37,1038,Edward Rice,54.0,HR,44936.000000,2019-05-03,False
38,1039,Paul Shaffer,31.0,IT,65119.000000,2021-08-23,False
39,1040,Benjamin Lucas,39.0,HR,76407.000000,2024-01-12,False
41,1042,Phillip Ford,58.0,Marketing,57133.000000,2015-06-18,False
42,1043,Amanda Davis,55.0,HR,41059.000000,2021-06-21,False
43,1044,Mary Cole,25.0,IT,49209.000000,2023-11-29,False
44,1045,Joan Davis,57.0,IT,81102.000000,2023-10-19,False
45,1046,Taylor Brown,45.5,Marketing,64772.000000,2019-11-24,False
46,1047,Jamie Jones,52.0,HR,53015.000000,2021-12-20,False
49,1050,Stacy Torres,37.0,Finance,62178.000000,2018-04-17,False
51,1052,Brandon Lynch,52.0,Marketing,65593.000000,2018-02-07,False
53,1054,Renee Wolfe,58.0,HR,59643.923913,2016-05-27,False
56,1057,Kyle Steele,42.0,HR,42417.000000,2018-09-28,False
58,1059,Michael Alvarez,27.0,Finance,69470.000000,2020-04-11,False
59,1060,Holly Rodriguez,41.0,HR,85452.000000,2024-10-09,False
61,1062,Suzanne Vargas,45.5,Marketing,79996.000000,2018-01-18,False
70,1071,Michael Barnes,23.0,Finance,42842.000000,2015-12-22,False
71,1072,David Martinez,36.0,Finance,49729.000000,2021-05-01,False
74,1075,Mary Shepard,25.0,Marketing,54416.000000,2022-09-20,False
75,1076,Veronica Price,36.0,IT,55419.000000,2017-06-26,False
80,1081,Evelyn Smith,45.5,Marketing,59643.923913,2016-04-17,False
85,1086,Phyllis Allen,41.0,HR,73328.000000,2022-10-16,False
86,1087,Stephen King,45.0,HR,68345.000000,2016-11-17,False
87,1088,Scott Hernandez,52.0,Finance,68451.000000,2020-09-10,False
90,1091,Jack Bernard,31.0,HR,43676.000000,2017-05-06,False
91,1092,Andres Carlson,45.0,Marketing,59643.923913,2021-07-22,False
93,1094,Patrick Smith,45.5,IT,41643.000000,2016-07-04,False
94,1095,Michael Gilbert,28.0,Finance,60860.000000,2021-04-03,False
96,1097,Matthew Alexander,25.0,IT,61221.000000,2018-11-18,False
97,1098,Kelly Cole,25.0,HR,69045.000000,2018-07-14,False
99,1100,Paul Price MD,45.5,Marketing,42862.000000,2017-12-27,False

In [196]:
logger.info('Rows after filtering 1 is: ' + str(df[fil1].shape))

2026-03-11 08:54:14,359 - my_logger - INFO - Rows after filtering 1 is: (49, 7)
INFO:my_logger:Rows after filtering 1 is: (49, 7)

In [197]:
df['years_in_company'] = (pd.Timestamp.now() - df['joining_date']).dt.days / 365
df

,employee_id,name,age,department,salary,joining_date,resigned,years_in_company
0,1001,Steven Dunn,30.0,IT,46846.000000,2024-06-09,False,1.753425
1,1002,Jennifer Romero,54.0,IT,43585.000000,2018-02-07,False,8.093151
2,1003,Dana Haney,59.0,Finance,59643.923913,2019-01-11,False,7.167123
3,1004,Louis Powers,60.0,Finance,58094.000000,2019-09-26,False,6.460274
4,1005,Jennifer Gilmore,54.0,Marketing,80848.000000,2020-02-09,False,6.087671
...,...,...,...,...,...,...,...,...
95,1096,John Walton,28.0,IT,52401.000000,2017-08-13,True,8.580822
96,1097,Matthew Alexander,25.0,IT,61221.000000,2018-11-18,False,7.315068
97,1098,Kelly Cole,25.0,HR,69045.000000,2018-07-14,False,7.663014
98,1099,Melissa Harper,52.0,IT,61606.000000,2022-10-20,True,3.391781
99,1100,Paul Price MD,45.5,Marketing,42862.000000,2017-12-27,False,8.208219

In [198]:
logger.info('Added column years_in_comppany via timetstamp - joining date')

2026-03-11 08:54:14,402 - my_logger - INFO - Added column years_in_comppany via timetstamp - joining date
INFO:my_logger:Added column years_in_comppany via timetstamp - joining date

### Task 4: Aggregation & Analysis
*   Compute department-level statistics including average salary and median age.
*   Apply a salary increment of 10% for employees belonging to a specific department.
*   Log analytical results and changes applied.

In [199]:
df.groupby('department').agg({'salary': 'mean', 'age': 'median'})

                  salary   age
department
Finance     58612.570938  45.5
HR          60466.443028  45.0
IT          57740.778872  46.5
Marketing   62476.088587  45.5

In [200]:
logger.info('Computed department-level statistics including average salary and median age.')

2026-03-11 08:54:14,434 - my_logger - INFO - Computed department-level statistics including average salary and median age.
INFO:my_logger:Computed department-level statistics including average salary and median age.

In [201]:
df.loc[df['department'] == 'IT', 'salary'] = df['salary'] * 1.10
df

,employee_id,name,age,department,salary,joining_date,resigned,years_in_company
0,1001,Steven Dunn,30.0,IT,51530.600000,2024-06-09,False,1.753425
1,1002,Jennifer Romero,54.0,IT,47943.500000,2018-02-07,False,8.093151
2,1003,Dana Haney,59.0,Finance,59643.923913,2019-01-11,False,7.167123
3,1004,Louis Powers,60.0,Finance,58094.000000,2019-09-26,False,6.460274
4,1005,Jennifer Gilmore,54.0,Marketing,80848.000000,2020-02-09,False,6.087671
...,...,...,...,...,...,...,...,...
95,1096,John Walton,28.0,IT,57641.100000,2017-08-13,True,8.580822
96,1097,Matthew Alexander,25.0,IT,67343.100000,2018-11-18,False,7.315068
97,1098,Kelly Cole,25.0,HR,69045.000000,2018-07-14,False,7.663014
98,1099,Melissa Harper,52.0,IT,67766.600000,2022-10-20,True,3.391781
99,1100,Paul Price MD,45.5,Marketing,42862.000000,2017-12-27,False,8.208219

In [202]:
logger.info('it depertment got 10 percent increment')

2026-03-11 08:54:14,479 - my_logger - INFO - it depertment got 10 percent increment
INFO:my_logger:it depertment got 10 percent increment

### Task 5: Data Transformation & Export
*   Rename columns where required to improve clarity.
*   Retain only relevant fields in the final dataset (`Employee_ID`, `Name`, `Age`, `Department`, `Salary`, and `YearsInCompany`).
*   Sort the data based on joining date in descending order.
*   Export the final dataset to JSON format.
*   Log successful data export and record count.

In [203]:
df.rename(columns={'resigned': 'has_resigned'})

,employee_id,name,age,department,salary,joining_date,has_resigned,years_in_company
0,1001,Steven Dunn,30.0,IT,51530.600000,2024-06-09,False,1.753425
1,1002,Jennifer Romero,54.0,IT,47943.500000,2018-02-07,False,8.093151
2,1003,Dana Haney,59.0,Finance,59643.923913,2019-01-11,False,7.167123
3,1004,Louis Powers,60.0,Finance,58094.000000,2019-09-26,False,6.460274
4,1005,Jennifer Gilmore,54.0,Marketing,80848.000000,2020-02-09,False,6.087671
...,...,...,...,...,...,...,...,...
95,1096,John Walton,28.0,IT,57641.100000,2017-08-13,True,8.580822
96,1097,Matthew Alexander,25.0,IT,67343.100000,2018-11-18,False,7.315068
97,1098,Kelly Cole,25.0,HR,69045.000000,2018-07-14,False,7.663014
98,1099,Melissa Harper,52.0,IT,67766.600000,2022-10-20,True,3.391781
99,1100,Paul Price MD,45.5,Marketing,42862.000000,2017-12-27,False,8.208219

In [204]:
final_df = df[['employee_id', 'name', 'age','department', 'salary', 'years_in_company']]
final_df

,employee_id,name,age,department,salary,years_in_company
0,1001,Steven Dunn,30.0,IT,51530.600000,1.753425
1,1002,Jennifer Romero,54.0,IT,47943.500000,8.093151
2,1003,Dana Haney,59.0,Finance,59643.923913,7.167123
3,1004,Louis Powers,60.0,Finance,58094.000000,6.460274
4,1005,Jennifer Gilmore,54.0,Marketing,80848.000000,6.087671
...,...,...,...,...,...,...
95,1096,John Walton,28.0,IT,57641.100000,8.580822
96,1097,Matthew Alexander,25.0,IT,67343.100000,7.315068
97,1098,Kelly Cole,25.0,HR,69045.000000,7.663014
98,1099,Melissa Harper,52.0,IT,67766.600000,3.391781
99,1100,Paul Price MD,45.5,Marketing,42862.000000,8.208219

In [205]:
final_df.sort_values(by='years_in_company', ascending=False, inplace=True)
final_df

/tmp/ipykernel_623/4016776322.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.sort_values(by='years_in_company', ascending=False, inplace=True)

,employee_id,name,age,department,salary,years_in_company
63,1064,Elizabeth Thompson,56.0,Finance,72278.0,11.123288
8,1009,Lori Short,56.0,IT,64432.5,11.038356
19,1020,Robert Jackson,30.0,Marketing,48234.0,11.000000
17,1018,Bryan Golden,30.0,Finance,78126.0,10.852055
6,1007,Thomas Lopez,39.0,HR,66678.0,10.805479
...,...,...,...,...,...,...
0,1001,Steven Dunn,30.0,IT,51530.6,1.753425
28,1029,Lauren Santos,50.0,HR,41990.0,1.723288
33,1034,April Yoder,55.0,Finance,53113.0,1.641096
59,1060,Holly Rodriguez,41.0,HR,85452.0,1.419178
72,1073,Stephanie Hanson,45.5,IT,94227.1,1.290411

In [206]:
final_df.to_json('final.json')

In [207]:
logger.info('exported the data to json and the row count is' + str(final_df.shape))

2026-03-11 08:54:14,591 - my_logger - INFO - exported the data to json and the row count is(100, 6)
INFO:my_logger:exported the data to json and the row count is(100, 6)